name: resume_room
description: An application created with Flutter to find resumenes of people
  with the same interests as you.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^2.3.0
  bot_toast: ^4.0.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0
  get_it: ^7.2.0
  injectable: ^1.4.1
  intl: ^0.17.0

dev_dependencies:
  auto_route_generator: ^2.1.0
  build_runner: ^2.1.1
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.2.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.4.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/font/
    - assets/images/

  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/font/PlusJakartaSans-ExtraBoldItalic.ttf
          style: italic
        - asset: assets/font/PlusJakartaSans-ExtraBold.ttf
        - asset: assets/font/PlusJakartaSans-BoldItalic.ttf
          style: italic
        - asset: assets/font/PlusJakartaSans-Bold.ttf
        - asset: assets/font/PlusJakartaSans-MediumItalic.ttf
          style: italic
        - asset: assets/font/PlusJakartaSans-Medium.ttf
        - asset: assets/font/PlusJakartaSans-Italic.ttf
          style: italic
        - asset: assets/font/PlusJakartaSans-Regular.ttf
        - asset: assets/font/PlusJakartaSans-LightItalic.ttf
          style: italic
        - asset: assets/font/PlusJakartaSans-Light.ttf
        - asset: assets/font/PlusJakartaSans-ExtraLightItalic.ttf
          style: italic
        - asset: assets/font/PlusJakartaSans-ExtraLight.ttf

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/brand_logo.png
